include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart ]
errors:
  missing_required_param: warning
  missing_return: warning
  todo: ignore
linter:
  rules:
    cascade_invocations: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false

